@startuml ChatModel
!theme blueprint

' docs/diagrams/plantuml/chat_model.puml

class ConfigurationManager extends Singleton {
    // JSONMap = Dict[str, Any]
    - MappingTemplate _map_template
    + ConfigurationManager(file_path: str, initial_data: Optional[JSONMap])
    + bool load()
    + bool save()
    + bool backup()
    + Any get_value(key: str, default: Optional[Any])
    + bool set_value(key: str, value: Any)
    + Optional[str] evaluate_path(key: str, default: Optional[Any])
    + str get_environment(variable: str)
}

class ChatCompletionMessage {
    + role: Literal["assistant", "user", "system"]
    + content: str
    + user: NotRequired[str]
}

class ChatModelChatCompletion extends ChatCompletionMessage {
    + role: Literal["assistant", "user", "system", "function"]
    + content: NotRequired[str]
    + function_call: NotRequired[str]
    + function_args: NotRequired[str]
    + user: NotRequired[str]
}

abstract class ChatModel {
    // ChatModelVector = Union[List[int], List[float]]
    // ChatModelEncoding = ChatModelVector
    // ChatModelEmbedding = List[ChatModelVector]
    - ConfigurationManager _config
    + ChatModel(config: ConfigurationManager)
    + ChatModelTextCompletion get_completion(prompt: str)
    + ChatModelChatCompletion get_chat_completion(messages: List[ChatModelChatCompletion])
    + ChatModelEmbedding get_embedding(input: Union[str, List[str]])
    + ChatModelEncoding get_encoding(text: str)
}

class ChatModelFactory{
    // Provider is one of: openai, llama, llama_cpp, etc...
    - ConfigurationManager _config
    - Dict[str, Callable] _provider_map
    + ChatModelFactory(config: ConfigurationManager):
    + create_model(provider: str) ChatModel
}

ChatModelFactory --> ChatModel : <<creates>>
ChatModelFactory::_config o--> ConfigurationManager
ChatModel::_config o--> ConfigurationManager
ChatModel --> ChatModelChatCompletion : <<uses>>

@enduml