@startuml ConfigurationManager
!theme blueprint

' docs/diagrams/plantuml/configuration_manager.puml

class MetaSingleton extends Type {
    # Dict[Type[object], object] _instances
    # Dict[Type[object], object] __call__(cls, *args, **kwargs)
    # MetaSingleton()
}

class Singleton extends MetaSingleton {
    # Singleton()
}

class ConfigurationManager extends Singleton {
    - Path file_path
    - JSONTemplate json_template
    - MappingTemplate map_template
    + ConfigurationManager(file_path: str, initial_data: Optional[dict[str, Any]])
    + bool load()
    + bool save()
    + bool backup()
    + Any get_value(key: str, default: Optional[Any])
    + bool set_value(key: str, value: Any)
    + str get_env_variable(env_var: str)
}

JSONTemplate o--> ConfigurationManager::json_template : <<JSONTemplate>>
MappingTemplate o--> ConfigurationManager::map_template : <<MappingTemplate>>
@enduml
