@startuml ConfigurationManager
!theme blueprint

' docs/diagrams/plantuml/configuration_manager.puml

class MetaSingleton extends Type {
    # Dict[Type, object] _instances
    # Dict[Type, object] __call__(cls, *args, **kwargs)
    # MetaSingleton()
}

class Singleton extends MetaSingleton {
    # Singleton()
}

class ConfigurationManager extends Singleton {
    // JSONMap = Dict[str, Any]
    - MappingTemplate _map_template
    + ConfigurationManager(file_path: str, initial_data: Optional[JSONMap])
    + bool load()
    + bool save()
    + bool backup()
    + Any get_value(key: str, default: Optional[Any])
    + bool set_value(key: str, value: Any)
    + Optional[str] evaluate_path(key: str, default: Optional[Any])
    + str get_environment(variable: str)
}

MappingTemplate o--> ConfigurationManager::map_template
@enduml
