@startuml MappingTemplates
!theme blueprint

class JSONTemplate {
    // JSONMap = Dict[str, Any]
    // JSONList = List[Dict[str, Any]]
    // JSONData = Union[JSONMap, JSONList]
    - Path _file_path
    - Optional[JSONData] _data
    + JSONTemplate(file_path: str, initial_data: Optional[JSONData])
    # Path file_path
    # JSONData data
    + bool load_json()
    + bool save_json()
    + bool backup_json()
    + bool make_directory()
}

class ListTemplate extends JSONTemplate {
    // JSONList = List[Dict[str, Any]]
    + ListTemplate(file_path: str, initial_data: Optional[JSONList])
    # int length
    + None append(item: Dict[str, Any])
    + bool insert(index: int, item: Dict[str, Any])
    + Optional[Dict[str, Any]] get(index: int)
    + bool update(index: int, item: Dict[str, Any])
    + bool remove(index: int)
    + None clear()
}

class MappingTemplate extends JSONTemplate {
    // JSONMap = Dict[str, Any]
    + MappingTemplate(file_path: str, initial_data: Optional[JSONMap])
    # List[str] keys
    + bool create(key: str, value: Any)
    + bool create_nested(value: Any, *keys: str)
    + Any read(key: str)
    + Any read_nested(*keys: str)
    + bool update(key: str, value: Any)
    + bool update_nested(value: Any, *keys: str)
    + bool delete(key: str)
    + bool delete_nested(*keys: str)
}

class ConfigurationManager
MappingTemplate <|.. ConfigurationManager

class ContextWindowManager
ListTemplate <|.. ContextWindowManager

class TranscriptManager
ListTemplate <|.. TranscriptManager
@enduml
