@startuml SessionQueue
!theme blueprint

' docs/diagrams/plantuml/session_queue.puml

class ConfigurationManager extends Singleton, MappingTemplate {
  - Path file_path
  - dict data
  + dict load()
  + None save()
  + None backup()
  + Any get_value()
  + bool set_value()
  + str get_env_variable()
}

class ChatModel {
  + str name
  + int max_tokens
  + int reserve
  + int length
  + dict system_message
  + ChatCompletionMessage get_chat_completions()
  + EmbedData get_embeddings()
}

class ChatModelFactory {
  - ConfigurationManager config
  - dict provider_map
  + ChatModel create_model()
}

class ChatSessionTokenManager {
  - provider: str
  - config: ConfigurationManager
  - model: ChatModel
  + reserve: float
  + offset: int
  + max_length: int
  + max_tokens: int
  + upper_limit: int
  + base_limit: int
  + __init__()
  + get_sequence_length(): int
  + get_message_length(): int
  + get_total_message_length(): int
  + is_overflow(): bool
}

class SessionPolicy extends Singleton {
  - ConfigurationManager config
  {static} is_file_path()
  {static} is_traversable()
  + bool is_accessible()
  + tuple is_command_allowed()
}

class SessionQueue {
  - ConfigurationManager config
  - ChatSessionTokenManager token
  - SessionPolicy policy
  - ChatModelFactory factory
  - ChatModel model
  - list transcript
  - list messages
  - string identifier
  + str dir_path
  + ChatCompletionMessage last_message
  + str last_role
  + str last_content
  + str last_function
  + FileHistory history
  + None set_session_name()
  + dict pop_message()
  + list dequeue()
  + None enqueue()
  + list extend()
  + ChatCompletionMessage get_completion()
  + None clear_messages()
  + None clear_transcript()
  + None clear_all()
  - None make_directory()
  + None save()
  + None load()
}

' Define relationships

SessionQueue o-- ConfigurationManager : uses >
SessionQueue o-- ChatSessionTokenManager : uses >
SessionQueue o-- SessionPolicy : uses >
SessionQueue o-- ChatModel : uses >
ChatSessionTokenManager o-- ChatModel : uses >
ChatModelFactory o-- ChatModel : creates >
SessionQueue o-- ChatModelFactory : uses >
@enduml