graph TB
  userExec["User Execution"] -- "Uses chat.py" --> chatPy["chat.py"]
  userExec -- "Uses embed.py" --> embedPy["embed.py"]
  chatPy -- "Load JSON Config" --> settingJson["Mapping Template"]
  embedPy -- "Load JSON Config" --> settingJson
  settingJson -- "Configuration Mapping" --> globalConfig[Global Configuration]
  globalConfig -- "Session Exists?" --> sessionInvokation[Session Invocation]
  sessionInvokation -- "No" --> newSession[New Session]
  newSession -- "Prompt for Label" --> promptLabel[Prompt for Label]
  promptLabel -- "Create Label" --> createLabel[Create Label]
  createLabel -- "Prompt for System Prompt" --> systemPrompt[System Prompt]
  systemPrompt -- "Create Session" --> createSession[Create Session]
  createSession -- "Open Context Window" --> contextWindow[Context Window]
  contextWindow -- "Context Enqueue" --> chatLoop[Chat Loop]
  chatLoop -- "Prompt User for Input" --> promptInput[Prompt User for Input]
  promptInput -- "User Inputs Message/Command" --> userInputMsgCmd[User Inputs Message/Command]
  userInputMsgCmd -- "Model Responds/Accesses Functions" --> modelResponds[Model Responds/Accesses Functions]
  modelResponds -- "Context Dequeue" --> dequeue[Dequeue]
  modelResponds -- "Model Accesses Memory" --> longTermMemory[Long Term Memory]
  dequeue -- "Embed dequeued tokens" --> embeddingsModel[Embeddings Model]
  embeddingsModel -- "Generate embeddings" --> embeddingsData[Embeddings Data]
  embeddingsData -- "Add embeddings" --> vectorDb[Vector Database]
  vectorDb -- "User Exits embed.py" --> userExitEmbed[User exits]
  vectorDb -- "Long Term Memory" --> longTermMemory
  longTermMemory -- "Return to Chat Loop" --> chatLoop
  longTermMemory -- "Model Memory Recall" --> modelResponds
  chatLoop -- "User Exits chat.py" --> userExit[User Exits]
  sessionInvokation -- "Yes" --> existingSession[Existing Session]
  existingSession -- "Prompt for Label" --> promptLabel2[Prompt for Label]
  promptLabel2 -- "Load Existing Session" --> loadExistingSession[Load Existing Session]
  loadExistingSession -- "Open Context Window" --> contextWindow
  globalConfig -- "Embed input data" --> embeddingsModel
  style contextWindow fill:#008B57
  style chatLoop fill:#008B8B
