graph TB
  script["Script"] -- "JSON Input" --> functionJson["function.json"]
  script -- "JSON Input" --> modelJson["model.json"]
  script -- "JSON Input" --> promptJson["prompt.json"]
  script -- "JSON Input" --> settingJson["setting.json"]
  settingJson -- "Application Preferences" --> macd
  functionJson -- "Function Metadata" --> macd["Model, Application, and Context Configuration"]
  modelJson -- "Model Preferences" --> macd
  promptJson -- "System Prompts" --> macd
  macd -- "User Preferences" --> globalConfig["Global Configuration"]
  globalConfig -- "Local or Remote Ingest" --> vectorDb["Vector Database"]
  globalConfig -- "Local or Remote Model" --> inferenceModel["Model for Inference"]
  globalConfig -- "Policy Settings" --> modelPermissions["Model Permissions"]
